"""
Django settings for KBStats project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Optionally load a local .env file for development (python-dotenv). This is
# optional: if python-dotenv isn't installed the project will continue to
# read environment variables normally. Do NOT commit a real `.env` file.
try:
    from dotenv import load_dotenv
    # BASE_DIR is defined below; temporarily compute path relative to this file
    _BASE_DIR = Path(__file__).resolve().parent.parent
    load_dotenv(dotenv_path=_BASE_DIR / '.env')
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "SECRET_KEY environment variable is not set. "
        "Please set it in your .env file (local) or environment variables (production)."
    )

# SECURITY WARNING: don't run with debug turned on in production!
# Allow overriding via environment variable; default to False.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Riot API key: read from environment variable `RIOT_API_KEY`.
# Do NOT commit your real API key into source control.
# Set `RIOT_API_KEY` in the environment or via your deployment platform.
RIOT_API_KEY = os.environ.get('RIOT_API_KEY') or None
ALLOWED_HOSTS = ['kbstats-preapp-main.onrender.com', 'www.kbstats.es', 'kbstats.es', 'localhost', '127.0.0.1']


# Application definition
# APPS DE ADMIN/AUTH DESACTIVADAS POR SEGURIDAD - Aplicación totalmente estática
INSTALLED_APPS = [
    # 'django.contrib.admin',  # DESACTIVADO
    # 'django.contrib.auth',  # DESACTIVADO
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',  # DESACTIVADO
    # 'django.contrib.messages',  # DESACTIVADO
    'django.contrib.staticfiles',
    'KBStats.Cinturones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # 'django.contrib.sessions.middleware.SessionMiddleware',  # DESACTIVADO
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',  # DESACTIVADO
    # 'django.contrib.messages.middleware.MessageMiddleware',  # DESACTIVADO
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KBStats.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',  # DESACTIVADO
                # 'django.contrib.messages.context_processors.messages',  # DESACTIVADO
            ],
        },
    },
]

WSGI_APPLICATION = 'KBStats.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# DESACTIVADO - No se necesita autenticación
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Static files (for production)
# Collect static into `STATIC_ROOT` and serve with WhiteNoise (or a CDN)
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Optional: include a project-level `static/` folder during development
STATICFILES_DIRS = [BASE_DIR / 'static']

# Use WhiteNoise storage to serve compressed files with long-term caching.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
