# Generated by Django 5.2.8 on 2026-05-15 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Jugadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Temporadas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('jugadores', models.ManyToManyField(related_name='equipos', to='Kblix.jugador')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='Kblix.temporada')),
            ],
            options={
                'verbose_name_plural': 'Equipos',
                'ordering': ['nombre', 'temporada__nombre'],
                'unique_together': {('nombre', 'temporada')},
            },
        ),
    ]
