# Generated by Django 5.2.8 on 2025-11-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='Cinturones.equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=100, unique=True)),
                ('jornada', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_partida', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion_segundos', models.IntegerField(default=0)),
                ('dragones_azul', models.IntegerField(default=0)),
                ('dragones_rojo', models.IntegerField(default=0)),
                ('heraldos_azul', models.IntegerField(default=0)),
                ('heraldos_rojo', models.IntegerField(default=0)),
                ('barones_azul', models.IntegerField(default=0)),
                ('barones_rojo', models.IntegerField(default=0)),
                ('elders_azul', models.IntegerField(default=0)),
                ('elders_rojo', models.IntegerField(default=0)),
                ('atakhan_azul', models.IntegerField(default=0)),
                ('atakhan_rojo', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo_azul', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_azul', to='Cinturones.equipo')),
                ('equipo_rojo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas_rojo', to='Cinturones.equipo')),
                ('ganador_equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ganadas', to='Cinturones.equipo')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='StatsJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeon', models.CharField(blank=True, max_length=100, null=True)),
                ('kills', models.IntegerField(default=0)),
                ('muertes', models.IntegerField(default=0)),
                ('asistencias', models.IntegerField(default=0)),
                ('kda', models.FloatField(default=0.0)),
                ('kp_porcentaje', models.FloatField(default=0.0)),
                ('oro', models.IntegerField(default=0)),
                ('dano_infligido', models.BigIntegerField(default=0)),
                ('porcentaje_dano_equipo', models.FloatField(default=0.0)),
                ('dano_min', models.FloatField(default=0.0)),
                ('dano_recibido', models.BigIntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('cs_min', models.FloatField(default=0.0)),
                ('vision_score', models.IntegerField(default=0)),
                ('double_kills', models.IntegerField(default=0)),
                ('triple_kills', models.IntegerField(default=0)),
                ('quadra_kills', models.IntegerField(default=0)),
                ('penta_kills', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Cinturones.jugador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_jugadores', to='Cinturones.partida')),
            ],
            options={
                'verbose_name': 'Estadística de Jugador',
                'verbose_name_plural': 'Estadísticas de Jugadores',
                'unique_together': {('partida', 'jugador')},
            },
        ),
    ]
