# Generated by Django 5.2.8 on 2025-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinturones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsjugador',
            name='equipo_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='statsjugador',
            name='rol',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
