# Generated by Django 5.2.8 on 2026-03-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinturones', '0002_statsjugador_equipo_nombre_statsjugador_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statsjugador',
            name='oro',
        ),
        migrations.RemoveField(
            model_name='statsjugador',
            name='vision_score',
        ),
        migrations.AddField(
            model_name='statsjugador',
            name='oro_min',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='statsjugador',
            name='vision_min',
            field=models.FloatField(default=0.0),
        ),
    ]
