# Generated by Django 5.2.8 on 2026-04-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinturones', '0003_remove_statsjugador_oro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsjugador',
            name='game_time',
            field=models.FloatField(default=0.0),
        ),
    ]
