# Generated by Django 5.2.8 on 2026-04-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinturones', '0004_statsjugador_game_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsjugador',
            name='dano_oro',
            field=models.FloatField(default=0.0),
        ),
    ]
