# Generated by Django 5.2.8 on 2026-05-26 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinturones', '0008_statsjugador_early_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutedPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jugador Scouted',
                'verbose_name_plural': 'Jugadores Scouted',
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(max_length=100)),
                ('puuid', models.CharField(blank=True, max_length=200)),
                ('is_main', models.BooleanField(default=False)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='Cinturones.scoutedplayer')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'unique_together': {('player', 'riot_id')},
            },
        ),
        migrations.CreateModel(
            name='ScoutedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=50)),
                ('game_start', models.BigIntegerField(default=0)),
                ('game_duration', models.IntegerField(default=0)),
                ('queue_id', models.IntegerField(default=0)),
                ('champion_name', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('team_id', models.IntegerField(default=100)),
                ('win', models.BooleanField(default=False)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('cs', models.IntegerField(default=0)),
                ('vision_score', models.IntegerField(default=0)),
                ('damage_dealt', models.IntegerField(default=0)),
                ('gold_earned', models.IntegerField(default=0)),
                ('position_data', models.JSONField(blank=True, null=True)),
                ('jungle_stats', models.JSONField(blank=True, null=True)),
                ('participants', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouted_matches', to='Cinturones.playeraccount')),
            ],
            options={
                'verbose_name': 'Partida Scouted',
                'verbose_name_plural': 'Partidas Scouted',
                'ordering': ['-game_start'],
                'unique_together': {('account', 'match_id')},
            },
        ),
    ]
